/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Hurry Edge API
 * Hurry Edge API is a REST API.
 * OpenAPI spec version: 1.0.0
 */
import axios, { AxiosRequestConfig, AxiosResponse } from 'axios'
import type {
  GetRetailers200,
  CreateRetailer200,
  CreateRetailerBody,
  GetRetailer200,
  UpdateRetailer200,
  UpdateRetailerBody,
} from './types.schemas'

/**
 * Fetchs all Retailers.

 * @summary Get all Retailers for admin
 */
export const getRetailers = <TData = AxiosResponse<GetRetailers200>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/retailers`, options)
}

/**
 * Create a new Retailer.

 * @summary Create a Retailer
 */
export const createRetailer = <TData = AxiosResponse<CreateRetailer200>>(
  createRetailerBody: CreateRetailerBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/retailers`, createRetailerBody, options)
}

/**
 * Fetch a single Retailer given its Retailer id.

 * @summary Get a Retailer
 */
export const getRetailer = <TData = AxiosResponse<GetRetailer200>>(
  retailerId: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/retailers/${retailerId}`, options)
}

/**
 * Updates an Reatilers's name, location, and details

 * @summary Updates a Retailers's details
 */
export const updateRetailer = <TData = AxiosResponse<UpdateRetailer200>>(
  retailerId: string,
  updateRetailerBody: UpdateRetailerBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.patch(`/retailers/${retailerId}`, updateRetailerBody, options)
}

export type GetRetailersResult = AxiosResponse<GetRetailers200>
export type CreateRetailerResult = AxiosResponse<CreateRetailer200>
export type GetRetailerResult = AxiosResponse<GetRetailer200>
export type UpdateRetailerResult = AxiosResponse<UpdateRetailer200>
