// Generated by ts-to-zod
import { z } from 'zod'

export const getRetailers200MetadataSchema = z.object({
  last_key: z.string().optional(),
})

export const operatingHourSchema = z.object({
  open: z.string(),
  close: z.string(),
})

export const operatingHoursSchema = z.object({
  sunday: z.array(operatingHourSchema).nullable(),
  monday: z.array(operatingHourSchema).nullable(),
  tuesday: z.array(operatingHourSchema).nullable(),
  wednesday: z.array(operatingHourSchema).nullable(),
  thursday: z.array(operatingHourSchema).nullable(),
  friday: z.array(operatingHourSchema).nullable(),
  saturday: z.array(operatingHourSchema).nullable(),
})

export const contactSchema = z.object({
  name: z.string().optional(),
  phone: z.string().optional(),
  instructions: z.string().optional(),
})

export const addressSchema = z.object({
  line_one: z.string(),
  line_two: z.string().optional(),
  city: z.string(),
  district: z.string().optional(),
  state: z.string().optional(),
  postal_code: z.string(),
  country: z.string().optional(),
  country_code: z.string(),
})

export const coordinatesSchema = z.object({
  lat: z.number(),
  lon: z.number(),
})

export const locationSchema = z.object({
  coordinates: coordinatesSchema,
  address: addressSchema,
})

export const createRetailerBodySchema = z.object({
  name: z.string(),
  location: locationSchema.optional(),
  contact: contactSchema.optional(),
})

export const retailerSchema = z.object({
  id: z.string(),
  name: z.string(),
  location: locationSchema,
  contact: contactSchema.optional(),
  operating_hours: operatingHoursSchema,
  default_delivery_time: z.string().optional(),
  default_max_travel_time: z.number().optional(),
  timezone: z.string().optional(),
})

export const updateRetailer200DataSchema = z.object({
  retailer: retailerSchema,
})

export const updateRetailer200Schema = z.object({
  data: updateRetailer200DataSchema,
})

export const updateRetailerBodySchema = z.object({
  name: z.string().optional(),
  location: locationSchema.optional(),
  contact: contactSchema.optional(),
})

export const getRetailer200DataSchema = z.object({
  retailer: retailerSchema,
})

export const getRetailer200Schema = z.object({
  data: getRetailer200DataSchema,
})

export const createRetailer200DataSchema = z.object({
  retailer: retailerSchema,
})

export const createRetailer200Schema = z.object({
  data: createRetailer200DataSchema,
})

export const getRetailers200DataSchema = z.object({
  retailers: z.array(retailerSchema),
})

export const getRetailers200Schema = z.object({
  metadata: getRetailers200MetadataSchema,
  data: getRetailers200DataSchema,
})
