/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Hurry Edge API
 * Hurry Edge API is a REST API.
 * OpenAPI spec version: 1.0.0
 */
export type UpdateRetailer200Data = {
  retailer: Retailer
}

export type UpdateRetailer200 = {
  data: UpdateRetailer200Data
}

export type UpdateRetailerBody = {
  name?: string
  location?: Location
  contact?: Contact
}

export type GetRetailer200Data = {
  retailer: Retailer
}

export type GetRetailer200 = {
  data: GetRetailer200Data
}

export type CreateRetailer200Data = {
  retailer: Retailer
}

export type CreateRetailer200 = {
  data: CreateRetailer200Data
}

export type GetRetailers200Data = {
  retailers: Retailer[]
}

export type GetRetailers200Metadata = {
  last_key?: string
}

export type GetRetailers200 = {
  metadata: GetRetailers200Metadata
  data: GetRetailers200Data
}

export interface OperatingHour {
  /** Opening time of the retailer */
  open: string
  /** Closing time of the retailer */
  close: string
}

export interface OperatingHours {
  sunday: OperatingHour[] | null
  monday: OperatingHour[] | null
  tuesday: OperatingHour[] | null
  wednesday: OperatingHour[] | null
  thursday: OperatingHour[] | null
  friday: OperatingHour[] | null
  saturday: OperatingHour[] | null
}

export interface Contact {
  /** The contact's name */
  name?: string
  /** The contact's phone number */
  phone?: string
  /** Any relevant instructions for the contact */
  instructions?: string
}

export interface Address {
  /** The first line of the address */
  line_one: string
  /** The second line of the address */
  line_two?: string
  /** The city name. */
  city: string
  /** The district name */
  district?: string
  /** The state name. */
  state?: string
  /** The postal code or zip code. */
  postal_code: string
  /** The country or region name. */
  country?: string
  /** The ISO country code for the country or region using the ISO 3166-1 alpha-2 standard. */
  country_code: string
}

export interface Coordinates {
  /** Latitude */
  lat: number
  /** Longitude */
  lon: number
}

export interface Location {
  /** The location's coordinates */
  coordinates: Coordinates
  /** The location's address */
  address: Address
}

export type CreateRetailerBody = {
  name: string
  location?: Location
  contact?: Contact
}

export interface Retailer {
  /** The auto generated UUID of the retailer */
  id: string
  /** The retailer's name */
  name: string
  /** The retailer's location */
  location: Location
  /** The retailer's contact */
  contact?: Contact
  /** The retailer's hours */
  operating_hours: OperatingHours
  /** default time of day when deliveries should be completed */
  default_delivery_time?: string
  /** Default number of minutes a task can be in transit for this retailer */
  default_max_travel_time?: number
  /** The timezone of the retailer. */
  timezone?: string
}
